project:
  type: book

book:
  title: 'Title: TBD'
  author: 'Your Name'
  date: 'July 2023'
  description: "A thesis submitted to Macquarie University for the degree of Master of Research"
  chapters:
    - index.qmd
    - abstract.qmd
    - statement.qmd
    - acknowledgements.qmd
    - dedication.qmd
    - list_of_publication.qmd
    - introduction.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-conclusion.qmd"
  appendices:
    - "A-appA.qmd"
  references: refs.qmd
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. © 2023, Your name"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"

# toc-title: "<b>Table of Contents</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "MMMM YYYY"
number-depth: 2
bibliography: thesis.bib
csl: apa-single-spaced.csl
reporttype: thesis # or report or assignment
degreeorunit: degree #or a unit such as STAT8081
degreename: 'Master of Research'
school: School of Mathematical & Physical Sciences
institution: 'Macquarie University'
division: "Examiner's Copy"
submitted: 2023
execute:
  # freeze: auto
  # re-render computational documents only when source changes
  echo: true
  warning: false
  message: false
  fig-height: 3.8
  fig-width: 6.3

format:
  html:
    theme:
      - cosmo
      - thesis.scss
    fontsize: 16px
    mainfont: "Merriweather, serif"
    code-link: true
    html-math-method: katex
    include-in-header:
      file: header.html
  mqthesis-pdf:
    keep-tex: true
